### PR TITLE
Update zendservice-google-gcm

### PR DESCRIPTION
**Pull request by az-iar**
bump zendframework/zendservice-google-gcm version which update to use fcm as mentioned in #16

### CODE REVIEW

**Comment by barryvdh** [comment]
Does this need to change anything for existing apps? Is this a breaking change?

**Comment by az-iar** [comment]
no changes needed. the api still remain the same

**Comment by OwenMelbz** [comment]
@barryvdh do you know if theres any intentions on tagging this for release any time soon?

**Comment by barryvdh** [comment]
I merged this 3 months ago?

**Comment by OwenMelbz** [comment]
Sorry I meant tagging for release - currently when you try install via the readme, you seem to get a failure.

```
composer require laravel-notification-channels/gcm
Using version ^0.0.1 for laravel-notification-channels/gcm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel-notification-channels/gcm ^0.0.1 -> satisfiable by laravel-notification-channels/gcm[0.0.1].
    - Conclusion: don't install zendframework/zendservice-google-gcm 2.0.0
    - laravel-notification-channels/gcm 0.0.1 requires zendframework/zendservice-google-gcm ^1.0 -> satisfiable by zendframework/zendservice-google-gcm[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - Can only install one of: zendframework/zendservice-google-gcm[1.0.0, 2.0.0].
    - Can only install one of: zendframework/zendservice-google-gcm[1.0.1, 2.0.0].
    - Can only install one of: zendframework/zendservice-google-gcm[1.0.2, 2.0.0].
    - Can only install one of: zendframework/zendservice-google-gcm[1.0.3, 2.0.0].
    - Installation request for zendframework/zendservice-google-gcm (locked at 2.0.0) -> satisfiable by zendframework/zendservice-google-gcm[2.0.0].
```

I'm needing to add `"laravel-notification-channels/gcm": "dev-master"` into my composer json rather than using a version, I guess 0.0.2 is next?

**Comment by barryvdh** [comment]
You should be able to use `0.1.x@dev`

**Comment by OwenMelbz** [comment]
That also seems to work :D, excuse me for being stupid but

- What the difference between that and `dev-master`?
- Is there a reason it's not under an incremental release like `0.0.2`?
- Where/how are people meant to find out that's what they need to use rather than just a normal require?

Thanks :)

**Comment by barryvdh** [comment]
I've tagged this as 0.2.0

**Pull request merged**
