### PR TITLE
Mirate to FCM & added the missing parameters

### PR DESCRIPTION
**Pull request by LonnyX**
As this package is based on Zend GCM, this pull request will not be accepted. But Hope you will understand the issue and correct by yourself.

### CODE REVIEW

**Comment by barryvdh** [comment]
What is the issue exactly? Isn't FCM something different?

**Comment by LonnyX** [comment]
Hi, nop, it's the same thing. [Google migrated to Firebase](https://developers.google.com/cloud-messaging/) . The problem is that the API changed a little bit and it's not working anymore based on Zend GCM. I make it works by adding the missing params. 
Here is my version: https://github.com/LonnyX/ZendService_Google_Gcm

**Comment by barryvdh** [comment]
Okay I see some PR's there already. Let's see if they accept them :)

**Comment by LonnyX** [comment]
Hmm, I don't think they will accept soon. Maybe I will create a new package for FCM without using their module.

**Comment by mathieutu** [comment]
Hi, @LonnyX have you tried after the merged PR about FCM? Is it working now? 
Thanks!

**Comment by dwightwatson** [comment]
I don't think switching off Zend to your own repo is the way to go.

Judging from zendframework/ZendService_Google_Gcm#25 it seems as though FCM support has been added upstream.

I'm a bit uneasy about adding FCM support to this package because it's called GCM - I would think that we should create a new package or rename it to match. Regardless we have #21 open so we can word toward supporting FCM in a future release.

**Pull request closed without merging**
