### PR TITLE
Add auto discover service provider

### PR DESCRIPTION
**Pull request by az-iar**

### CODE REVIEW

**Comment by mathieutu** [comment]
Just pinging @freekmurze to merge this little useful thing.
Thanks!

**Comment by freekmurze** [comment]
I’m not the maintainer of this package.

**Comment by mathieutu** [comment]
hum.. you're marked as the owner.
Do you know who can we ping for that?
Or can you do it anyway? Because it's just the classical autodiscovering, and nothing else, so anyone can merge that without any doubt!

**Comment by freekmurze** [comment]
I'm thinking @barryvdh is the maintainer. 

(I'm one of the owners of the GitHub organisation. When starting this effort we agreed with the package maintainers that they would have full control and we as owners don't intervene in their work).

**Comment by barryvdh** [comment]
Ah missed this, thanks!

**Comment by mathieutu** [comment]
Thanks guys! 🎉

**Pull request merged**
